# Generated by Django 5.2 on 2025-05-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioFile',
        ),
    ]
